-- =====================================================================
-- sql/schema.sql
-- Unified Supabase schema — Django-compatible + JS admin extensions
--
-- Run once in the Supabase SQL editor (Dashboard → SQL Editor → New query).
-- Safe to re-run: CREATE IF NOT EXISTS + ADD COLUMN IF NOT EXISTS.
-- =====================================================================

-- ── 1. Core tables (Django-compatible names & columns) ───────────────

-- Single-row profile record
CREATE TABLE IF NOT EXISTS site_profile (
  id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name        text        NOT NULL DEFAULT '',
  name_alt         text                 DEFAULT '',
  title            text                 DEFAULT '',
  department_1     text                 DEFAULT '',
  department_2     text                 DEFAULT '',
  university       text                 DEFAULT '',
  address          text                 DEFAULT '',
  office           text                 DEFAULT '',
  phone            text                 DEFAULT '',
  email            text                 DEFAULT '',
  photo_url        text                 DEFAULT '',
  biography        text                 DEFAULT '',
  scholar_url      text                 DEFAULT '',
  researchgate_url text                 DEFAULT '',
  linkedin_url     text                 DEFAULT '',
  github_url       text                 DEFAULT '',
  orcid_url        text                 DEFAULT '',
  students_text    text                 DEFAULT '',
  students_email   text                 DEFAULT '',
  updated_at       timestamptz          DEFAULT now()
);

CREATE TABLE IF NOT EXISTS news_items (
  id         bigint  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  event_date date,
  body       text    NOT NULL DEFAULT '',
  sort_order int     NOT NULL DEFAULT 0,
  visible    boolean NOT NULL DEFAULT true
);
ALTER TABLE news_items ADD COLUMN IF NOT EXISTS visible boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS research_interests (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  label      text   NOT NULL DEFAULT '',
  sort_order int    NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS education_entries (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  degree      text   NOT NULL DEFAULT '',
  institution text   NOT NULL DEFAULT '',
  sort_order  int    NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS publications (
  id         bigint  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pub_id     text    NOT NULL DEFAULT '',
  pub_type   text    NOT NULL DEFAULT 'journal',
  citation   text    NOT NULL DEFAULT '',
  pdf_url    text             DEFAULT '',
  doi_url    text             DEFAULT '',
  slides_url text             DEFAULT '',
  award_note text             DEFAULT '',
  year       int,
  sort_order int     NOT NULL DEFAULT 0,
  visible    boolean NOT NULL DEFAULT true
);
ALTER TABLE publications ADD COLUMN IF NOT EXISTS visible    boolean NOT NULL DEFAULT true;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS citation   text             DEFAULT '';
ALTER TABLE publications ADD COLUMN IF NOT EXISTS award_note text             DEFAULT '';

CREATE TABLE IF NOT EXISTS teaching_courses (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  label       text   NOT NULL DEFAULT '',
  institution text             DEFAULT '',
  sort_order  int    NOT NULL DEFAULT 0
);
ALTER TABLE teaching_courses ADD COLUMN IF NOT EXISTS institution text DEFAULT '';

CREATE TABLE IF NOT EXISTS awards (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  label      text   NOT NULL DEFAULT '',
  year       int,
  sort_order int    NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS service_entries (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  category   text   NOT NULL DEFAULT '',
  label      text   NOT NULL DEFAULT '',
  sort_order int    NOT NULL DEFAULT 0
);

-- ── 2. New tables for JS admin ────────────────────────────────────────

-- Controls nav labels, order, and visibility per section
CREATE TABLE IF NOT EXISTS site_sections (
  id         bigint  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug       text    NOT NULL UNIQUE,
  label      text    NOT NULL DEFAULT '',
  sort_order int     NOT NULL DEFAULT 0,
  visible    boolean NOT NULL DEFAULT true
);

-- Extra pages added from the admin dashboard
CREATE TABLE IF NOT EXISTS custom_pages (
  id         bigint  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug       text    NOT NULL UNIQUE,
  title      text    NOT NULL DEFAULT '',
  content    text             DEFAULT '',
  sort_order int     NOT NULL DEFAULT 0,
  visible    boolean NOT NULL DEFAULT true
);

-- ── 3. Row-Level Security ─────────────────────────────────────────────

ALTER TABLE site_profile       ENABLE ROW LEVEL SECURITY;
ALTER TABLE news_items         ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE education_entries  ENABLE ROW LEVEL SECURITY;
ALTER TABLE publications       ENABLE ROW LEVEL SECURITY;
ALTER TABLE teaching_courses   ENABLE ROW LEVEL SECURITY;
ALTER TABLE awards             ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_entries    ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_sections      ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_pages       ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  r   RECORD;
  tbl text;
BEGIN
  -- Drop every existing policy on all affected tables (handles any name)
  FOR r IN
    SELECT tablename, policyname FROM pg_policies
    WHERE schemaname = 'public'
    AND tablename IN (
      'site_profile','news_items','research_interests','education_entries',
      'publications','teaching_courses','awards','service_entries',
      'site_sections','custom_pages'
    )
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
  END LOOP;

  -- Recreate: public SELECT + authenticated full access
  FOREACH tbl IN ARRAY ARRAY[
    'site_profile','news_items','research_interests','education_entries',
    'publications','teaching_courses','awards','service_entries',
    'site_sections','custom_pages'
  ] LOOP
    EXECUTE format('CREATE POLICY "public_read" ON public.%I FOR SELECT USING (true)', tbl);
    EXECUTE format(
      'CREATE POLICY "auth_all" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)',
      tbl
    );
  END LOOP;
END $$;

-- ── 4. Storage bucket "profile" (public photo uploads) ───────────────

INSERT INTO storage.buckets (id, name, public)
VALUES ('profile', 'profile', true)
ON CONFLICT (id) DO NOTHING;

DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT policyname FROM pg_policies
    WHERE schemaname = 'storage' AND tablename = 'objects'
      AND (policyname ILIKE '%profile_public%' OR policyname ILIKE '%profile_auth%'
        OR policyname ILIKE '%profile_bucket%')
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON storage.objects', r.policyname);
  END LOOP;
END $$;

CREATE POLICY "profile_public_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'profile');

CREATE POLICY "profile_auth_insert"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'profile');

CREATE POLICY "profile_auth_update"
  ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'profile');

CREATE POLICY "profile_auth_delete"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'profile');

-- ── 5. Seed site_sections (skip if already populated) ────────────────

INSERT INTO site_sections (slug, label, sort_order, visible)
SELECT slug, label, sort_order, visible FROM (VALUES
  ('biography',    'Biography',       1, true),
  ('news',         'News',            2, true),
  ('research',     'Research',        3, true),
  ('education',    'Education',       4, true),
  ('publications', 'Publications',    5, true),
  ('teaching',     'Teaching',        6, true),
  ('awards',       'Honors & Awards', 7, true),
  ('service',      'Service',         8, true)
) AS v(slug, label, sort_order, visible)
WHERE NOT EXISTS (SELECT 1 FROM site_sections)
ON CONFLICT (slug) DO NOTHING;

-- ── 6. Seed site_profile (skip if already populated) ─────────────────

INSERT INTO site_profile (
  full_name, name_alt, title,
  department_1, department_2, university,
  address, office, phone, email,
  biography,
  scholar_url, researchgate_url, linkedin_url, github_url, orcid_url,
  students_text, students_email
)
SELECT
  'Your Name',
  '（姓名）',
  'Assistant Professor',
  'Department of Electrical and Computer Engineering',
  'Department of Computer Science (Courtesy)',
  'North Carolina State University',
  '890 Oval Dr, Raleigh, NC 27695',
  '3072 Engr Bldg II',
  '(919) 515-5128',
  'you@university.edu',
  E'I am an Assistant Professor in the Department of Electrical and Computer Engineering at North Carolina State University, where I direct the Intelligent Wireless Networking (iWN) Laboratory. My work addresses software-defined wireless systems, intelligent edge computing, and learning-driven network resource management.\n\nPreviously, I held postdoctoral and research appointments at institutions in the United States. I received the Ph.D. in Electrical and Computer Engineering from the Georgia Institute of Technology, and the B.S. and M.S. in Electrical Engineering from the National Taiwan University.',
  'https://scholar.google.com/',
  'https://www.researchgate.net/',
  'https://www.linkedin.com/',
  'https://github.com/',
  'https://orcid.org/',
  E'I am recruiting self-motivated Ph.D. students in wireless communications and networking. Current openings emphasize 6G radio and intelligent networking, vehicular edge computing, and wireless federated learning.\n\nTo inquire, send your CV and transcripts by email.',
  'you@university.edu'
WHERE NOT EXISTS (SELECT 1 FROM site_profile);

-- ── 7. Seed news_items ────────────────────────────────────────────────

INSERT INTO news_items (event_date, body, sort_order, visible)
SELECT event_date, body, sort_order, visible FROM (VALUES
  ('2025-06-01'::date, 'Paper on federated learning for multi-mission UAV operations accepted at AFRL Summer VFRP.', 1, true),
  ('2025-03-01'::date, 'Two papers accepted at IEEE INFOCOM 2025.', 2, true),
  ('2024-11-01'::date, 'Runner-up, AFRL Software Defined Radio Challenge, for distributed multimedia transmission.', 3, true),
  ('2024-07-01'::date, 'Journal article on O-RAN resource management published in <em>IEEE Transactions on Mobile Computing</em>.', 4, true),
  ('2024-05-01'::date, 'Received Faculty Research Grant from NASA North Carolina Space Grant for 6G serverless computing architecture.', 5, true)
) AS v(event_date, body, sort_order, visible)
WHERE NOT EXISTS (SELECT 1 FROM news_items);

-- ── 8. Seed research_interests ───────────────────────────────────────

INSERT INTO research_interests (label, sort_order)
SELECT label, sort_order FROM (VALUES
  ('Wireless software-defined networking and open RAN architectures', 1),
  ('Intelligent edge computing and network slicing', 2),
  ('Federated and distributed machine learning over wireless links', 3),
  ('Resource management for vehicular and UAV communication systems', 4),
  ('Underground and underwater wireless communications', 5),
  ('Security and reliability in IoT and cyber-physical systems', 6)
) AS v(label, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM research_interests);

-- ── 9. Seed education_entries ────────────────────────────────────────

INSERT INTO education_entries (degree, institution, sort_order)
SELECT degree, institution, sort_order FROM (VALUES
  ('Ph.D., Electrical and Computer Engineering', 'Georgia Institute of Technology, Atlanta, GA', 1),
  ('M.S., Communications Engineering',           'National Taiwan University, Taipei, Taiwan',   2),
  ('B.S., Electrical Engineering',               'National Taiwan University, Taipei, Taiwan',   3)
) AS v(degree, institution, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM education_entries);

-- ── 10. Seed publications ────────────────────────────────────────────

INSERT INTO publications (pub_id, pub_type, citation, pdf_url, doi_url, slides_url, award_note, year, sort_order, visible)
SELECT pub_id, pub_type, citation, pdf_url, doi_url, slides_url, award_note, year::int, sort_order, visible FROM (VALUES
  ('J5', 'journal',
   '<strong>Your Name</strong>, A. Collaborator, and B. Collaborator, &ldquo;DRL-ORAN Platform for Large-Scale Networking Resource Management,&rdquo; <em>IEEE Transactions on Mobile Computing</em>, vol. 23, no. 8, pp. 7421&ndash;7436, 2024.',
   '#', '#', '', '', '2024', 1, true),
  ('J4', 'journal',
   'C. Collaborator, <strong>Your Name</strong>, and D. Collaborator, &ldquo;QoS-Aware Adaptive Routing in Multi-Layer Hierarchical SDNs,&rdquo; <em>IEEE Transactions on Network and Service Management</em>, 2020.',
   '#', '', '', '', '2020', 2, true),
  ('C8', 'conference',
   '<strong>Your Name</strong>, F. Collaborator, and G. Collaborator, &ldquo;Federated Learning over Open RAN: Architecture and Prototype,&rdquo; in <em>Proc. IEEE INFOCOM</em>, 2025.',
   '#', '', '#', '', '2025', 3, true),
  ('C7', 'conference',
   'H. Collaborator and <strong>Your Name</strong>, &ldquo;Signal Interference Management in O-RAN xAPP Design,&rdquo; in <em>Proc. IEEE ICC</em>, 2021.',
   '#', '', '', '', '2021', 4, true),
  ('C6', 'conference',
   '<strong>Your Name</strong>, I. Collaborator, and J. Collaborator, &ldquo;Home Network Intelligent Scheduling Control,&rdquo; in <em>Proc. IEEE GLOBECOM</em>, 2021.',
   '#', '', '', 'Best Paper Award Runner-up', '2021', 5, true),
  ('W1', 'workshop',
   '<strong>Your Name</strong> and K. Collaborator, &ldquo;Demo: A Prototype Platform for 5G Edge Analytics,&rdquo; in <em>Proc. ACM MobiCom Demo</em>, 2022.',
   '#', '', '', '', '2022', 6, true)
) AS v(pub_id, pub_type, citation, pdf_url, doi_url, slides_url, award_note, year, sort_order, visible)
WHERE NOT EXISTS (SELECT 1 FROM publications);

-- ── 11. Seed teaching_courses ────────────────────────────────────────

INSERT INTO teaching_courses (label, institution, sort_order)
SELECT label, institution, sort_order FROM (VALUES
  ('ECE 566 — Wireless Networking and Mobile Computing (Fall 2024, Spring 2025)', 'North Carolina State University', 1),
  ('ECE 792 — Special Topics: Open RAN and Network Softwarization (Spring 2024)',  'North Carolina State University', 2),
  ('ECE 302 — Introduction to Communication Systems (Fall 2023)',                  'North Carolina State University', 3)
) AS v(label, institution, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM teaching_courses);

-- ── 12. Seed awards ──────────────────────────────────────────────────

INSERT INTO awards (label, year, sort_order)
SELECT label, year::int, sort_order FROM (VALUES
  ('<strong>Awardee</strong>, Summer Visiting Faculty Research Program (VFRP), Air Force Research Laboratory.', '2025', 1),
  ('<strong>Runner-up</strong>, Software Defined Radio Challenge, AFRL.',                                        '2024', 2),
  ('<strong>AI4AI Research Award</strong>, Meta.',                                                               '2022', 3),
  ('<strong>Faculty Research Grant</strong>, NASA North Carolina Space Grant.',                                  '2022', 4),
  ('<strong>Distinguished TPC Member Award</strong>, IEEE INFOCOM.',                                             '2020', 5),
  ('<strong>Researcher of the Year</strong>, Broadband Wireless Networking Laboratory, Georgia Tech.',           '2015', 6)
) AS v(label, year, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM awards);

-- ── 13. Seed service_entries ─────────────────────────────────────────

INSERT INTO service_entries (category, label, sort_order)
SELECT category, label, sort_order FROM (VALUES
  ('Technical Program Committees', 'IEEE INFOCOM (2020&ndash;present; Distinguished TPC Member, 2020)', 1),
  ('Technical Program Committees', 'IEEE ICC, IEEE GLOBECOM, ACM MobiCom',                              2),
  ('Journal Reviewing',            '<em>IEEE/ACM Transactions on Networking</em>',                      3),
  ('Journal Reviewing',            '<em>IEEE Transactions on Mobile Computing</em>',                    4),
  ('Journal Reviewing',            '<em>IEEE Transactions on Wireless Communications</em>',             5)
) AS v(category, label, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM service_entries);
